version: '2'
services:
  zeek:
    image: blacktop/zeek
    container_name: zeek
    restart: unless-stopped
    volumes:
     - /opt/zeek/logs:/pcap
     - /opt/zeek/config/local.zeek:/usr/local/zeek/share/zeek/site/local.zeek
    cap_add:
      - NET_RAW #or NET_ADMIN
    network_mode: "host"
    command: -i af_packet::ens192 local "Site::local_nets += { 192.168.0.0/16 }"