version: '2'
services:
  kibana:
    image: 'docker.elastic.co/kibana/kibana:7.4.2'
    container_name: kibana
    restart: unless-stopped
    labels:
      - "traefik.http.routers.kibana.rule=HostRegexp(`{subdomain:kibana.*}.{subdomain:.*}`)"
      - "traefik.enable=true"
      - "traefik.http.routers.kibana.entrypoints=web"
      - "traefik.http.routers.kibana.middlewares=th-auth"
    volumes:
      - /opt/threathunt/kibana/config/:/usr/share/kibana/config/
    ports:
      - '5601:5601'
    networks:
      - elastic
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: unless-stopped
    labels:
      - "traefik.http.routers.portainer.rule=HostRegexp(`{subdomain:portainer-elk.*}.{subdomain:.*}`)"
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=web"
    volumes:
    - /opt/threathunt/portainer/data:/data
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
    networks:
      - elastic      
  domainstats:
    image: securityonionsolutions/so-domainstats:latest
    container_name: domainstats
    restart: unless-stopped
    ports:
      - 20000:20000
    volumes:
      - /opt/threathunt/domain_stats/top-1m.csv:/opt/domain_stats/top-1m.csv
    networks:
      - elastic
  freqserver:
    image: securityonionsolutions/so-freqserver
    container_name: freqserver
    restart: unless-stopped
    ports:
      - 10004:10004
    networks:
      - elastic
  
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--providers.file.filename=dynamic_conf.toml"
      - "--providers.file.directory=/"
      - "--providers.file.watch=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.th-auth.basicauth.users=thadmin:$$apr1$$2RnW3J50$$bjzbmnFizHfUNlegGHFAN0"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/threathunt/traefik/dynamic_conf.toml:/dynamic_conf.toml
    restart: unless-stopped
    networks:
      - elastic
  mdbook:
    image: crimsoncorelabs/mdbook
    container_name: mdbook
    restart: unless-stopped
    volumes:
    - /opt/wiki:/opt/wiki
    ports:
      - 3000:3000
      - 3001:3001 
    labels:
      - "traefik.http.routers.mdbook.rule=HostRegexp(`{subdomain:mdbook.*}.{subdomain:.*}`)"
      - "traefik.enable=true"
      - "traefik.http.routers.mdbook.entrypoints=web"
      - "traefik.http.routers.mdbook.middlewares=th-auth"
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge

