[http]
  [http.routers]
    [http.routers.portainermq]
      entryPoints = ["web"]
      service = "portainermq"
      rule = "HostRegexp(`{subdomain:portainermq.*}.{subdomain:.*}`)"
    [http.routers.rabbitmq]
      entryPoints = ["web"]
      service = "rabbitmq"
      rule = "HostRegexp(`{subdomain:rabbitmq.*}.{subdomain:.*}`)" 
  [http.services]
    [http.services.portainermq]
      [http.services.portainermq.loadBalancer]
        passHostHeader = true
        [[http.services.portainermq.loadBalancer.servers]]
          url = "https://10.0.0.6"
    [http.services.rabbitmq]
      [http.services.rabbitmq.loadBalancer]
        passHostHeader = true
        [[http.services.rabbitmq.loadBalancer.servers]]
          url = "http://10.0.0.6:15672"