[http]
  [http.routers]
    [http.routers.portainermq]
      entryPoints = ["web"]
      service = "portainer-mq"
      rule = "HostRegexp(`{subdomain:portainer-mq.*}.{subdomain:.*}`)"
    [http.routers.rabbitmq]
      entryPoints = ["web"]
      service = "rabbitmq"
      rule = "HostRegexp(`{subdomain:rabbitmq.*}.{subdomain:.*}`)" 
  [http.services]
    [http.services.portainer-mq]
      [http.services.portainer-mq.loadBalancer]
        passHostHeader = true
        [[http.services.portainer-mq.loadBalancer.servers]]
          url = "http://10.0.0.6:9000"
    [http.services.rabbitmq]
      [http.services.rabbitmq.loadBalancer]
        passHostHeader = true
        [[http.services.rabbitmq.loadBalancer.servers]]
          url = "http://10.0.0.6:15672"