version: '2'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.4.2
    container_name: logstash    
    ports:
     - 5044:5044
    restart: unless-stopped
    volumes:
    - /opt/threathunt/logstash/pipeline/:/usr/share/logstash/pipeline/
    - /opt/threathunt/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
