version: '2'
services:
  cerebro:
    image: lmenezes/cerebro:latest
    container_name: cerebro
    restart: unless-stopped
    ports:
      - 9001:9000
    networks:
      - elastic
networks:
  elastic:
    driver: bridge